#!/bin/bash

#example return messages from FreeDns
#   Updated example.com to 11.11.11.111 in 0.022 seconds
#   ERROR: Invalid update URL (2)
#   ERROR: Address 11.11.11.111 has not changed.

FREEDNS_CONF="/etc/freedns/freedns.conf"
FREEDNS_URL="https://freedns.afraid.org/dynamic/update.php"

echo "started $0"

if [[ ! -f "${FREEDNS_CONF}" ]]; then
    echo "Error: ${FREEDNS_CONF} does not exist"
    exit 1    
fi

while IFS=" " read -r domain token; do
    STATUS="Error"
    MESSAGE=""

    #ignore comments
    if [[ "$domain" == *"#"* ]]; then
        continue

    # ignore empty lines
    elif [ -z "$domain" ]; then
        continue

    # eror if incomplete line found
    elif [ -z "$token" ]; then
        MESSAGE="token empty"

    else
        FREEDNS_RETURN=$(curl --insecure --silent "${FREEDNS_URL}?${token}")
        FREEDNS_EXITCODE=$?

        if [[ FREEDNS_EXITCODE -eq 0 ]]; then
            case "$FREEDNS_RETURN" in
                "Updated "*)
                    STATUS="Updated"
                    ;;

                "ERROR: Address "*" has not changed.")
                    STATUS="Unchanged"
                    ;;
            esac
        else
            EXIT_STATUS=1
        fi
        MESSAGE="FREEDNS_EXITCODE=[${FREEDNS_EXITCODE}], FREEDNS_RETURN=[${FREEDNS_RETURN}]"
    fi
    echo "${STATUS}: domain=[${domain}], token=[${token}], ${MESSAGE}"
done <"$FREEDNS_CONF"

echo "finished $0"
exit 0
